# Build stage


FROM node:lts-alpine AS build

# Set config
ENV NPM_CONFIG_UPDATE_NOTIFIER=false
ENV NPM_CONFIG_FUND=false

WORKDIR /app
COPY package*.json ./

RUN npm ci
COPY . ./
RUN npm run build

# Production stage
FROM caddy
WORKDIR /app
COPY Caddyfile ./
RUN caddy fmt Caddyfile --overwrite
COPY --from=build /app/out ./out
CMD ["caddy", "run", "--config", "Caddyfile", "--adapter", "caddyfile"]