"""add inital tables

Revision ID: 88c4d183c122
Revises: f8355e2dbc9c
Create Date: 2026-03-04 17:39:58.033558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c4d183c122'
down_revision: Union[str, Sequence[str], None] = 'f8355e2dbc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop posts first (FK to users), then change users.id to UUID before creating
    # tables that reference users.id with UUID.
    op.drop_table('posts')
    # Drop default on id (e.g. sequence) before changing type; then convert to UUID
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute(
        "ALTER TABLE users ALTER COLUMN id TYPE UUID USING gen_random_uuid()"
    )
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.add_column('users', sa.Column('date_created', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('trails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_papers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('has_read', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('last_read', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'paper_id')
    )
    op.create_table('paper_graph_edges',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('trail_id', sa.UUID(), nullable=False),
    sa.Column('next_node_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['next_node_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'trail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_graph_edges')
    op.drop_table('user_papers')
    op.drop_table('trails')
    op.drop_table('papers')
    op.drop_column('users', 'name')
    op.drop_column('users', 'date_created')
    # PostgreSQL requires USING to convert UUID -> INTEGER
    op.execute(
        "ALTER TABLE users ALTER COLUMN id TYPE INTEGER USING "
        "(('x' || left(replace(id::text, '-', ''), 8))::bit(32)::integer)"
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('posts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    # ### end Alembic commands ###
