"""add column topic to Trail

Revision ID: bcd0f9bc0fb4
Revises: 88c4d183c122
Create Date: 2026-03-04 20:29:19.446306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd0f9bc0fb4'
down_revision: Union[str, Sequence[str], None] = '88c4d183c122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trails', sa.Column('topic', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trails', 'topic')
    # ### end Alembic commands ###
